# Generated by Django 4.1 on 2022-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.URLField(null=True),
        ),
    ]
