# Generated by Django 4.1.3 on 2022-11-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_food', models.CharField(max_length=60)),
                ('gram_food', models.IntegerField()),
                ('cost_food', models.IntegerField()),
            ],
        ),
    ]
